spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/ocd-db
    username: postgres
    password: 123456
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: none

  mail:
    host: smtp.gmail.com
    port: 587
    username: ocdpsobrevida@gmail.com
    password: SocdP@2020
    properties.mail.smtp:
      auth: true
      connectiontimeout: 5000
      timeout: 5000
      writetimeout: 5000
      starttls.enable: true

  servlet.multipart:
    max-file-size: -1
    max-request-size: -1

flyway:
  database:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    