package br.ufg.api.ocd.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "localAtendimento")
public class LocalAtendimento {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String nome;
    @DynamoDBAttribute
    private Distrito distrito;
    @DynamoDBAttribute
    private TipoLocalAtendimento tipoLocalAtendimento;
    @DynamoDBAttribute
    private String emailResponsavel;
    @DynamoDBAttribute
    private String nomeResponsavel;
}
