package br.ufg.api.ocd.model;

import br.ufg.api.ocd.enums.TipoAtendimento;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;


@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "logAtendimentos")
public class LogAtendimentos {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String idPaciente;
    @DynamoDBAttribute
    private String idUltimoAtendimento;
    @DynamoDBAttribute
    private TipoAtendimento tipoAtendimento;
    @DynamoDBAttribute
    private LocalDateTime dataAtendimento;
    @DynamoDBAttribute
    private LocalDateTime dataSugeridaAcompanhamento;
    @DynamoDBAttribute
    private LocalDateTime dataSugeridaTratamento;
    @DynamoDBAttribute
    private String idLocalAtendimento;
    @DynamoDBAttribute
    private String idLocalEncaminhado;

    public void atualiza(Atendimento atendimento){
        this.setDataAtendimento(atendimento.getDataAtendimento());
        this.setDataSugeridaAcompanhamento(atendimento.getDataSugeridaAcompanhamento());
        this.setDataSugeridaTratamento(atendimento.getDataSugeridaTratamento());
        this.setIdLocalAtendimento(atendimento.getLocalAtendimento() != null ? atendimento.getLocalAtendimento().getId() : null);
        this.setIdLocalEncaminhado(atendimento.getLocalEncaminhado() != null ? atendimento.getLocalEncaminhado().getId() : null);
        this.setIdPaciente(atendimento.getPaciente() != null ? atendimento.getPaciente().getId() : null);
        this.setIdUltimoAtendimento(atendimento.getId());
        this.setTipoAtendimento(atendimento.getTipoAtendimento());
    }
}
