package br.ufg.api.ocd.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import java.io.File;


@Data
@DynamoDBTable(tableName = "procedimentosResultados")
public class ProcedimentosResultados {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private File anexo;
    @DynamoDBAttribute
    private String nome;
    @DynamoDBAttribute
    private String observacao;
    @DynamoDBAttribute
    private Atendimento atendimento;

}
