/*
 * Copyright (c) 2019. Universidade Federal de Goiás (UFG)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package br.ufg.api.ocd.model;

import br.ufg.api.ocd.enums.NivelAtencao;
import br.ufg.api.ocd.enums.StatusUsuario;
import br.ufg.api.ocd.enums.TipoUsuario;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "usuario")
public class Usuario {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String cpf;
    @DynamoDBAttribute
    private String nome;
    @DynamoDBAttribute
    private String senha;
    @DynamoDBAttribute
    private StatusUsuario status;
    @DynamoDBAttribute
    private String email;
    @DynamoDBAttribute
    private String telefone;
    @DynamoDBAttribute
    private NivelAtencao nivelAtencao;
    @DynamoDBAttribute
    private TipoUsuario tipoUsuario;
}